eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

application:
  jwt_secret: 551EAB3DDF696B8C3D5CCA520CED5980E79CFCEBBD15A42587983E22EBBC4E0B
  title: Pokedex - Mail Service
  version: 1.0.0

server:
  port: 8095

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: emailForgotPasswordTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: emailForgotPasswordId
    properties:
      spring.json.type.mapping: event:com.pokedex.mailservice.dto.ForgotPasswordEmailDto
  mail:
    host: smtp.gmail.com
    port: 587
    username: Iceshu4cyberbullies@gmail.com
    password: xnqryikbjfmiijho
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: mail-service