spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:${db.port}/ji
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  servlet:
    context-path: /java-ignite
  port: 8080
application:
  title: Java Ignite
  version: 1.0.0
db:
  port: 3306