spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/pokedex
    username: root
    password: ${MYSQL_PASSWORD}
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: redis
      port: 6379
      database: 0
