spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false


application:
  title: Pokedex - dev
  version: 1.0.0 - dev