spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  data:
    redis:
      host: localhostt



application:
  title: Pokedex - dev
  version: 1.0.0 - dev