INSERT INTO USERS (USERNAME, NAME, SURNAME, PASSWORD, ROLE, IS_ACTIVE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY,LAST_MODIFIED_DATE)
VALUES ("admin", "admin", "the ruler", "$2a$10$JKJKCH4/v67.0I2ETLbj8utWedgMNlkS3Zl3okF4uGt0Gx80OWXZe", "ADMIN", true,
        "SYSTEM", CURRENT_DATE(), "SYSTEM", CURRENT_DATE());

INSERT INTO USERS (USERNAME, NAME, SURNAME, PASSWORD, ROLE, IS_ACTIVE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY,LAST_MODIFIED_DATE)
VALUES ("test", "test", "user", "$2a$10$JKJKCH4/v67.0I2ETLbj8utWedgMNlkS3Zl3okF4uGt0Gx80OWXZe", "TRAINER", true,
        "SYSTEM", CURRENT_DATE(), "SYSTEM", CURRENT_DATE());