version: "3"
services:
  pokedexdb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokedex
    ports:
      - 3307:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 5

  redis:
    image: redis:7.0.5-alpine
    command: [ "redis-server", "--protected-mode", "no", "--bind", "0.0.0.0" ]
    restart: always
    hostname: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  server:
    environment:
      - MYSQL_HOST=pokedexdb
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=root
      - MAIL_PASSWORD=xnqryikbjfmiijho
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9080:8080
    depends_on:
      - pokedexdb
      - redis