spring:
  application:
    name: pokemon-service
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: create
      properties:
        hibernate:
          show_sql: false
          format_sql: false
          use_sql_comments: false
  main:
    banner-mode: console
  datasource:
    url: jdbc:mysql://localhost:${db.port}/pokedex_pokemon
    username: root
    password: Hoo.s5zi


db:
  port: 3306

application:
  title: Pokedex - Pokemon Microservice
  version: 1.0.0

server:
  port: 8081
  servlet:
    context-path: /pokedex

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka